#!/bin/env bash

if [ -z "$VAGRANT_VER" ]; then
	VAGRANT_VER="1.7.2_x86_64"
fi

vagrant__install() {
	basket__pushd ${BASKET__PATH_TEMP}
		if using_apt; then
			basket__wget https://dl.bintray.com/mitchellh/vagrant/vagrant_${VAGRANT_VER}.deb
			with_sudo dpkg -i vagrant_${VAGRANT_VER}.deb
		elif using_yum; then
			# :TODO: check dependencies
			basket__wget https://dl.bintray.com/mitchellh/vagrant/vagrant_${VAGRANT_VER}.rpm
			with_sudo rpm -Uvh vagrant_${VAGRANT_VER}.rpm
		else
			await_input "Vagrant installation is currently only available for Debian and Redhat based systems, sorry!"
		fi
	basket__popd
}
